format = "$directory$git_branch$git_status$character"

[directory]
truncation_length = 2
truncate_to_repo = true
style = "bold blue"
read_only = ""

[git_branch]
format = " [$branch]($style)"
style = "green"

[git_status]
format = " [$all_status$ahead_behind]($style)"
style = "yellow"
conflicted = "!"
modified = "!"
staged = "+"
untracked = "?"
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
deleted = "✘"

[aws]
disabled = true

[cmd_duration]
disabled = true
