# Keep prompt short
format = "$directory$git_branch$git_status$character"

[directory]
truncation_length = 2
truncate_to_repo = true
style = "bold"
read_only = ""

[git_branch]
format = " [$branch]($style)"
style = "bright-black"

[git_status]
format = " [$all_status$ahead_behind]($style)"
style = "bright-black"
conflicted = "!"
modified = "!"
staged = "+"
untracked = "?"
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
renamed = "»"
deleted = "✘"

# Disable cloud modules
[aws]
disabled = true

[gcloud]
disabled = true

[azure]
disabled = true

# Disable timing noise
[cmd_duration]
disabled = true
